version: '3.8'

services:
  praksonar-app:
    build: .
    container_name: praksonar-app
    ports:
      - "3000:3000"
    env_file: .env.local
    restart: unless-stopped
    environment:
      - NODE_ENV=production
